workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - credentials
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.tashlehkom.app" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate iOS files
        script: |
          flutter precache --ios
          flutter build ios --config-only
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    # publishing:
    #   app_store_connect:
    #     auth: integration
    #     submit_to_testflight: true

  android-workflow:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk

