workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic API Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tashlehkomv2.app
      vars:
        APP_STORE_CONNECT_ISSUER_ID: 23fde2fc-bad6-4a20-ac93-62f9c8090838
        APP_STORE_CONNECT_KEY_IDENTIFIER: 7GHHGS9K5W
        BUNDLE_ID: com.tashlehkomv2.app
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - credentials
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/ios/ipa/ExportOptions.plist
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers

  android-workflow:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk

