// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE',
    appId: 'YOUR_WEB_APP_ID_HERE',
    messagingSenderId: 'YOUR_SENDER_ID_HERE',
    projectId: 'tashlehekomv2-production',
    authDomain: 'tashlehekomv2-production.firebaseapp.com',
    databaseURL: 'https://tashlehekomv2-production-default-rtdb.firebaseio.com',
    storageBucket: 'tashlehekomv2-production.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID_HERE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: 'YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: 'YOUR_SENDER_ID_HERE',
    projectId: 'tashlehekomv2-production',
    databaseURL: 'https://tashlehekomv2-production-default-rtdb.firebaseio.com',
    storageBucket: 'tashlehekomv2-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: 'YOUR_IOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_SENDER_ID_HERE',
    projectId: 'tashlehekomv2-production',
    databaseURL: 'https://tashlehekomv2-production-default-rtdb.firebaseio.com',
    storageBucket: 'tashlehekomv2-production.appspot.com',
    iosBundleId: 'com.tashlehekomv2.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_SENDER_ID_HERE',
    projectId: 'tashlehekomv2-production',
    databaseURL: 'https://tashlehekomv2-production-default-rtdb.firebaseio.com',
    storageBucket: 'tashlehekomv2-production.appspot.com',
    iosBundleId: 'com.tashlehekomv2.app',
  );
}

/// إعدادات Firebase للإنتاج
/// يجب استبدال جميع القيم النموذجية بالقيم الحقيقية من Firebase Console
/// 
/// خطوات الحصول على القيم:
/// 1. الذهاب إلى Firebase Console: https://console.firebase.google.com/
/// 2. اختيار المشروع: tashlehekomv2-production
/// 3. الذهاب إلى Project Settings
/// 4. اختيار التطبيق المطلوب (Android/iOS/Web)
/// 5. نسخ القيم من SDK setup and configuration
/// 
/// ملاحظات مهمة:
/// - لا تشارك هذه القيم في أماكن عامة
/// - استخدم متغيرات البيئة للقيم الحساسة في CI/CD
/// - تأكد من تطابق package name مع Firebase Console
/// - فعّل الخدمات المطلوبة في Firebase Console:
///   * Authentication (Phone)
///   * Cloud Firestore
///   * Cloud Storage
///   * Cloud Messaging
///   * Analytics (اختياري)
/// 
/// أمثلة على القيم (يجب استبدالها):
/// - API Key: AIzaSyC7Kl8xQx9X8X8X8X8X8X8X8X8X8X8X8X8
/// - App ID: 1:123456789012:android:abcdef1234567890abcdef
/// - Sender ID: 123456789012
/// - Project ID: tashlehekomv2-production
