// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2C9sU4qN7P4Pai5lt3Kvp5qwFJ-LXbQE',
    appId: '1:281285545629:web:demo',
    messagingSenderId: '281285545629',
    projectId: 'tashlehekom',
    authDomain: 'tashlehekom.firebaseapp.com',
    storageBucket: 'tashlehekom.firebasestorage.app',
    measurementId: 'G-DEMO123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2C9sU4qN7P4Pai5lt3Kvp5qwFJ-LXbQE',
    appId: '1:281285545629:android:b376e828f73d0f24518e74',
    messagingSenderId: '281285545629',
    projectId: 'tashlehekom',
    storageBucket: 'tashlehekom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2C9sU4qN7P4Pai5lt3Kvp5qwFJ-LXbQE',
    appId: '1:281285545629:ios:demo',
    messagingSenderId: '281285545629',
    projectId: 'tashlehekom',
    storageBucket: 'tashlehekom.firebasestorage.app',
    iosBundleId: 'com.tashlehekom.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2C9sU4qN7P4Pai5lt3Kvp5qwFJ-LXbQE',
    appId: '1:281285545629:macos:demo',
    messagingSenderId: '281285545629',
    projectId: 'tashlehekom',
    storageBucket: 'tashlehekom.firebasestorage.app',
    iosBundleId: 'com.tashlehekom.app',
  );
}
